model_name: xbgoose/hubert-large-speech-emotion-recognition-russian-dusha-finetuned
processor_name: facebook/hubert-large-ls960-ft
fine_tune_strategy: lora
lora_rank: 8
lora_alpha: 16
lora_target_modules:
  - q_proj
  - v_proj
batch_size: 4
grad_accum_steps: 8
lr: 1.0e-4
epochs: 15
warmup_ratio: 0.05
run_name: hubert_large_lora
output_dir: outputs/hubert_large_lora
